# Generated by Django 5.0.4 on 2024-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0003_email_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='description', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_head',
            field=models.CharField(max_length=100),
        ),
    ]
