# Generated by Django 5.0.4 on 2024-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0004_question_description_alter_question_ques_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
