# Generated by Django 5.0.4 on 2024-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0008_alter_question_voters_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
