# Generated by Django 5.0.4 on 2024-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0009_choice_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='percentage',
        ),
        migrations.AddField(
            model_name='question',
            name='totalvotes',
            field=models.IntegerField(default=0),
        ),
    ]
