# Generated by Django 5.0.4 on 2024-05-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0010_remove_choice_percentage_question_totalvotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
