# Generated by Django 5.0.4 on 2024-05-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0011_delete_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='voters_email',
            field=models.TextField(default='Emails: '),
        ),
    ]
